sanity-io/visual-editing

packages/presentation/src/PresentationTool.tsx
The `overlay/navigate` event triggered after initial load was causing a reset of the open document state. Added a check so that `id` and `type` params are preserved on the first navigation.
Fixes ECO-290.
=> fix(presentation): preserve current document on initial navigation

packages/overlays/src/util/findNonInlineElement.ts
Replaces the use of the experimental `computedStyleMap` with `window.getComputedStyle` to get an element's `display` property. The former method is not supported by Firefox.
=> fix(overlays): use getComputedStyle over computedStyleMap

apps/nuxt/components/ElementOverlay.vue, packages/overlays/src/ui/Overlays.tsx, packages/overlays/src/ui/useChannel.tsx
This solution means that overlay elements will only render if either:
- The app is not in an iframe.
- The app is in an iframe the overlays channel connection status is `connected`.
Fixes ECO-289.
=> fix(overlays): only render overlays in iframe if channel is connected

apps/nuxt/pages/preview.vue, packages/channels/package.json, packages/channels/tsconfig.json, packages/core-loader/package.json, packages/core-loader/src/live-mode/enableLiveMode.ts, packages/core-loader/src/live-mode/parseAllowStudioOrigin.ts, packages/core-loader/src/types.ts, packages/core-loader/test/parseAllowStudioOrigin.test.ts, packages/core-loader/vitest.config.ts, packages/groq-store/package.json, packages/nuxt-loader/package.json, packages/overlays/package.json, packages/overlays/src/ui/Overlays.tsx, packages/overlays/src/ui/enableOverlays.tsx, packages/overlays/src/ui/useAllowStudioOrigin.ts, packages/overlays/src/ui/useChannel.tsx, packages/overlays/test/useAllowStudioOrigin.test.tsx, packages/overlays/vitest.config.ts, packages/presentation/package.json, packages/presentation/vitest.config.ts, packages/preview-kit-compat/package.json, packages/preview-url-secret/globals.d.ts, packages/preview-url-secret/package.json, packages/preview-url-secret/src/validateSecret.ts, packages/react-loader/package.json, packages/react-loader/test/createQueryStore.test-d.ts, packages/svelte-loader/package.json, packages/visual-editing-helpers/package.json, pnpm-lock.yaml
```ts
enableOverlay({
allowStudioOrigin: typeof location === 'undefined' ? 'http://localhost:3000' : location.origin,
}
useLiveMode({
allowStudioOrigin: typeof location === 'undefined' ? 'http://localhost:3000' : location.origin,
})
```
```ts
enableOverlay({
allowStudioOrigin: 'same-origin'
})
useLiveMode({
allowStudioOrigin: 'same-origin'
})
```
=> feat: add new `same-origin` option

packages/preview-url-secret/src/validatePreviewUrl.ts, packages/preview-url-secret/src/validateSecret.ts
It is currently not possible to use the `validatePreviewUrl` function from `@sanity/preview-url-secret` in a CloudFlare Worker, as the Worker runtime's `fetch` implementation (annoyingly) throws in the presence of the `cache` request init keyword instead of failing silently or simply providing an implementation stub.
Ideally, CloudFlare updates the Worker runtime to not throw in this case, as the `cache` option is part of the fetch standard. Until that happens, this PR allows users to opt out of setting the `cache: "no-store"` option in `validateSecret`'s request init object, allowing `@sanity/preview-url-secret` to be used in CloudFlare Workers.
Related issues:
-  https://github.com/cloudflare/workerd/issues/698
=> fix: allow opting out of `cache: no-store` fetch option in `@sanity/preview-url-secret`

apps/next/src/app/shoes/VisualEditing.tsx, apps/next/src/components/VisualEditing.tsx, apps/studio/sanity.config.ts, packages/channels/src/controller.ts, packages/channels/src/node.ts, packages/channels/src/types.ts, packages/presentation/src/PresentationTool.tsx, packages/presentation/src/preview/PreviewFrame.tsx, packages/presentation/src/preview/PreviewLocationInput.tsx, packages/presentation/src/types.ts, packages/preview-kit-compat/src/useDocumentsInUse.ts, packages/preview-url-secret/src/withoutSecretSearchParams.ts
Opt in to using it by:
```tsx
presentationTool({
unstable_showUnsafeShareUrl: true, // defaults to `false`
})
```
Once enabled there's now a share menu next to the location input, rather than inside it, that opens a popover:
When using the "Open preview" popup mode it's now live, just like the iframe preview:
https://github.com/sanity-io/visual-editing/assets/81981/46464e73-7126-4159-8ed5-c6e2bd1c7a5f
=> feat: add share URL button and improve popup window mode

apps/svelte/src/hooks.server.ts, apps/svelte/src/routes/shoes/+page.server.ts, apps/svelte/src/routes/shoes/[slug]/+page.server.ts, packages/react-loader/src/createQueryStore/server-only.ts, packages/react-loader/src/createQueryStore/universal.ts, packages/svelte-loader/README.md, packages/svelte-loader/src/createQueryStore.ts
`loadQuery` was defaulting to using `published` if a perspective was not passed explicitly. Users may want to set perspective at client level when calling `setServerClient`, this PR allows for that.
=> fix: use client perspective in loadQuery if not passed explicitly

packages/svelte-loader/src/defineUseQuery.ts
Last PR merged in a change that was using `update` over `set` as it made state comparison easier, but turns out it was still triggering unnecessary updates. This should fix that.
=> fix(svelte-loader): prevent unnecessary fetcher state updates

apps/studio/presentation/CustomNavigator.tsx, packages/presentation/package.json, packages/presentation/src/PresentationNavigateContext.ts, packages/presentation/src/PresentationNavigateProvider.tsx, packages/presentation/src/constants.ts, packages/presentation/src/getIntentState.ts, packages/presentation/src/plugin.tsx, pnpm-lock.yaml
`unstable_navigator` related improvements to support the following within Presentation:
- navigate to a document by ID
- navigate to a new document creation intent
=> feat(presentation): support create intent and document navigation

packages/react-loader/src/createQueryStore/server-only.ts, packages/react-loader/src/types.ts
In my application, I have a need to selectively set `useCdn` based on factors other than those that impact the current perspective or stega settings. So exposing this option when invoking `loadQuery` is required.
=> feat: add option to use cdn in loadquery

apps/next-no-cache/src/components/VisualEditing/PostMessageQueries.tsx, apps/next-server-only/src/components/VisualEditing/PostMessageQueries.tsx, packages/channels/src/controller.ts, packages/channels/src/node.ts, packages/channels/src/types.ts, packages/core-loader/src/live-mode/enableLiveMode.ts, packages/presentation/src/PresentationTool.tsx, packages/presentation/src/loader/LoaderQueries.tsx, packages/presentation/src/loader/RevalidateTags.tsx, packages/preview-kit-compat/src/useDocumentsInUse.ts, packages/visual-editing-helpers/src/types.ts, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/useChannel.tsx
Type updates to differentiate sent and received messages in various parts of the channels mechanism.
A nice to have as part of a larger bit of work, but submitting as a separate PR to avoid later merge conflicts.
=> refactor: specify send and receive channel message types

apps/studio/presentation/CustomNavigator.tsx, apps/studio/sanity.config.ts, packages/presentation/src/editor/DocumentPane.tsx, packages/presentation/src/getIntentState.ts, packages/presentation/src/router.ts, packages/presentation/src/types.ts, packages/presentation/src/useParams.ts
This adds support for [parameterized templates](https://www.sanity.io/docs/initial-value-templates#66d873e2136f).
Also fixes support for initial value templates, we ostensibly supported this via a search param but the value wasn't being passed in the `DocumentPaneNode`.
=> feat(presentation): support parameterized templates

packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/useChannel.tsx
Fixes failing overlays: Channel was stored as a ref, which means no reactivity, which is needed in order to render the Overlays element.
=> refactor(visual-editing): use state over ref for channel instance

apps/svelte/src/routes/shoes/[slug]/+page.svelte, packages/presentation/src/PresentationTool.tsx, packages/presentation/src/constants.ts, packages/presentation/src/types.ts, packages/presentation/src/useParams.ts, packages/visual-editing-helpers/src/types.ts, packages/visual-editing/src/ui/Meta.ts, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/VisualEditing.tsx
As part of displaying Presentation related intent links. PR does a few things:
- Adds a `CommentIntentProvider` for providing intent link data.
- Adds a new channel message type for reporting the document title.
- Adds an optional parameter to the navigation message type for explicitly providing a title.
=> feat: support comments intent

packages/presentation/src/PresentationTool.tsx
Prefixing with `chore` instead of `fix` since the comment intent feature isn't released yet.
`mode` should always use `presentation`, it can't use the custom name.
=> chore: support presentation tools with custom names

packages/visual-editing/README.md
This updates the Next.js app router example to the correct way of using `draftMode().isEnabled`.
=> doc: correct Next.js draftMode().isEnabled usage

packages/presentation/src/PresentationTool.tsx, packages/presentation/src/lib/debounce.ts, packages/presentation/src/useDocumentsOnPage.ts, packages/visual-editing-helpers/src/csm/transformSanityNodeData.ts, packages/visual-editing-helpers/src/types.ts, packages/visual-editing/src/index.ts, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/ElementOverlay.tsx, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/util/findSanityNodes.ts, packages/visual-editing/src/util/stega.ts
Adds document reporting from the `visual-editing` package. This means loaders or preview kit are not strictly required for reporting documents.
Each method of document reporting now provides a key to `setDocumentsOnPage`, so the cache can store them as separate objects, which are merged and deduped by when returned as `documentsOnPage`. The entire cache is replaced when some new documents are received and the frame url has changed.
Also removes some unnecessary JSON stringifying and parsing when traversing and decoding overlay nodes.
=> feat(visual-editing): report documents on page

packages/react-loader/README.md
Since 6.12.0 these are imported from the main package.
https://github.com/sanity-io/client/pull/495
Might want to update these references elsewhere as well: https://github.com/search?q=repo%3Asanity-io%2Fvisual-editing+%40sanity%2Fclient%2Fstega&type=code cc @stipsan
=> docs: fixed imports from stega client

packages/core-loader/package.json, packages/core-loader/src/createDataAttribute.ts, packages/core-loader/test/createDataAttribute.test.ts, packages/react-loader/src/index.ts, packages/svelte-loader/src/index.ts
- Is this trying to do too much within a single function?
- Are the type names too verbose?
| Function                                                           | Returns                              |
| ------------------------------------------------------------------ | ------------------------------------ |
| `createDataAttribute({baseUrl})`                                   | Function scoped to studio            |
| `createDataAttribute({baseUrl}, {id, type})`                       | Function scoped to studio & document |
| `createDataAttribute({baseUrl})({id, type})`                       | Function scoped to studio & document |
| `createDataAttribute({baseUrl}, {id, type}).scope(rootPath)`       | Function scoped to path              |
| `createDataAttribute({baseUrl})({id, …
=> feat(core-loader): createDataAttribute

packages/presentation/src/editor/DocumentPane.tsx, packages/presentation/src/panels/Panel.tsx
Finally, adds support for collapsed state and prevents overscroll.
Collapsed state is triggered at 640px, this could be adjusted.
https://github.com/sanity-io/visual-editing/assets/8467307/96919201-108f-4685-9d7f-9ee971a5bea3
=> fix(presentation): prevent horizontal scroll on narrow document pane

apps/next/README.md, apps/next/next.config.mjs, apps/next/package.json, apps/next/src/app/only-visual-editing/layout.tsx, packages/overlays/package.json, packages/visual-editing/package.json, packages/visual-editing/src/controller.ts, packages/visual-editing/src/util/findSanityNodes.ts, packages/visual-editing/src/util/stega.ts, pnpm-lock.yaml
Currently, if `enableVisualEditing` is used at the same time as the Vercel Toolbar it leads to a terrible overlapping overlays UX:
https://github.com/sanity-io/visual-editing/assets/81981/1cc24508-9dd4-4cd2-a5cb-ca0bf46e7a20
With the fix in this PR the behaviour changes to no longer overlap:
https://github.com/sanity-io/visual-editing/assets/81981/9b358dee-9a79-490c-be9b-b8aadc7e4b5e
=> fix: don't render overlays if the Vercel Toolbar is present

apps/svelte/src/routes/shoes-with-loaders/+page.svelte, apps/svelte/src/routes/shoes-with-loaders/[slug]/+page.svelte, packages/svelte-loader/src/defineUseQuery.ts, packages/svelte-loader/src/types.ts
A proposal for a little tweak to `useQuery` in the Svelte loader. Adds the ability to optionally pass a single object instead of three params.
Previously:
```ts
export let data: PageData;
const { query, params, options } = data;
const query = useQuery(query, params, options);
$: ({ data: product } = $query);
```
Now:
```ts
export let data: PageData;
const query = useQuery(data);
$: ({ data: product } = $query);
```
=> feat(svelte-loader): support passing single object to `useQuery`

packages/presentation/src/editor/DocumentPane.tsx
As reported in #1120, the introduction of collapsed state is causing several usability issues.
@stipsan This also backs up your comments about the inspect panel, although the problem expands beyond what I'd considered, full screen portable text editor completely obscuring live updates for example.
This PR reverts those changes, reintroducing the overflowing layout.
=> fix: revert use of collapsed state

packages/presentation/src/editor/ContentEditor.tsx, packages/presentation/src/editor/DocumentPane.tsx, packages/presentation/src/editor/DocumentPanel.tsx, packages/presentation/src/editor/PresentationPaneRouterProvider.tsx
Maintains the preview parameter when navigating to referenced documents from the document pane. Currently the preview parameter is lost, triggering the app to redirect to the initial preview URL.
=> fix(presentation): maintain preview param on reference link

packages/presentation/src/panels/Panel.tsx
I've noticed scrollbars appearing intermittently since the collapsed state commit was merged, panels seem to overflow by ~a pixel. This removes them.
=> fix(presentation): prevent panel vertical scroll

apps/studio/presentation/DebugStega.tsx, packages/presentation/src/PresentationTool.tsx, packages/presentation/src/components/Resizable.tsx, packages/presentation/src/components/Resizer.tsx, packages/presentation/src/document/PresentationDocumentHeader.tsx, packages/presentation/src/editor/DocumentListPane.tsx, packages/presentation/src/editor/DocumentPane.tsx, packages/presentation/src/panels/Panel.tsx, packages/presentation/src/panels/PanelResizer.tsx, packages/presentation/src/panels/Panels.tsx, packages/presentation/src/preview/IFrame.tsx, packages/presentation/src/preview/PreviewFrame.tsx, packages/visual-editing/src/ui/ElementOverlay.tsx, packages/visual-editing/src/ui/Overlays.tsx
Seeing a lot of smoke around issues like https://github.com/styled-components/styled-components/issues/4275 and it seems the best way to protect against it is to never do:
```tsx
import styled from 'styled-components'
```
and instead always use the named export:
```tsx
import {styled} from 'styled-components'
```
I've tried adding a guard in `@sanity/pkg-utils` that automatically protects against it, but got blocked by: https://github.com/rollup/rollup/issues/5265
=> fix: improve vite compat with styled-components

packages/visual-editing/src/ui/elementsReducer.ts
I'm not sure how I didn't pick up on this one before, or if this is a result of the focus path changes I made in core, but it seems it's currently possible to focus two disparate overlay elements:
1. Click an element in the app preview.
2. The corresponding field gains focus in the document pane.
3. Focus a **different** field in the document pane.
4. There will be two active overlay elements (the clicked element does not lose focus).
Looks like this was a side effect of attempting to capture "reflected" events that occur when clicking on an element. Clicked elements were just left in place, regardless of whether or not the reflected event had a matching id/path.
This PR fixes that, so focusing on a different field should correctly drop focus of the previously clicked element.
=> fix(visual-editing): prevent focusing both clicked and focused elements

packages/presentation/src/editor/PresentationPaneRouterProvider.tsx
=> fix: remove `unrecognized previewUrl prop on DOM element` warning

packages/presentation/src/panels/usePanelsStorage.ts
Sometimes the localStorage for panel sizes are corrupted, and it causes Presentation to render a WSOD since all panels effectively has zero width:
I don't have a consistent way of reproducing it, or an explanation for how it stores `null` values to begin with. Since I had a local repro I was able to test the fix though and confirm it is able to restore default panel settings when the localStorage state has `null` instead of numbers.
=> fix: panels should recover from broken local storage state

packages/presentation/src/usePreviewUrl.ts, packages/presentation/test/usePreviewUrl.test.tsx
When opening a route, like https://visual-editing-studio.sanity.build/next/app-router?preview=/404, the `preview=/404` state would "stick". You could navigate to other tools and workspaces, click on `Presentation` in the navbar, and it would keep loading the same initial `/404` route instead of falling back to the default route.
With this PR it now "unsticks", and as a side-effect if you click on the tool in the navbar it does a reset, which is useful in dev if the app you're previewing crashed.
=> fix: the intial `preview` param no longer "sticks" until page reload

packages/visual-editing/src/controller.ts, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/useController.tsx
Toggling "Edit" on and off currently causes the overlay controller instance to essentially be destroyed and recreated, meaning visibility of overlay elements is "lost" when in the off state.
This PR changes the behaviour so that the controller instance is maintained, along with the state which tracks elements, even when "Edit" mode is off. Instead just the elements themselves are activated and deactivated internally.
This has the side effect of preventing the documents on screen being reported each time "Edit" is toggled, which was in turn causing a loading state to be repeatedly displayed in the Document list.
=> fix(visual-editing): maintain overlay element registration when toggling

apps/astro/package.json, apps/astro/src/pages/shoes/[slug].astro, apps/astro/src/pages/shoes/index.astro, apps/studio/sanity.config.ts
I've also configured the `SANITY_STUDIO_ASTRO_PREVIEW_URL` env var of the studio on Vercel to point to `https://visual-editing-astro.sanity.build/shoes`.
=> feat(studio): configure Astro presentation workspace URL

packages/presentation/src/useMainDocument.ts
In embedded Studios the `previewUrl` option typically won't have `origin` specified, leading to a crash:
Tested this fix on https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/pull/505
I would write a test for it but I feel we should fast track a fix and ask Studio DX to do a patch of `sanity` and circle back later instead, since everyone on embedded studios are currently unable to use Presentation Tool 😅
=> fix: regression causing a crash in embedded studios

packages/presentation/src/PresentationTool.tsx
When investigating #1486 inside
https://github.com/sanity-io/template-nextjs-personal-website I found that the `liveQueries` in `PresentationTool` easily run into an infinite loop causing the component to crash due to `Maximum update depth exceeded`. When inspecting the changes to the `liveQueries` that caused the re-renders I didn't find any differences expect a slight difference in `receivedAt`. Proceeding with the investigation, I couldn't find any odd places where `setLiveQueries` was called or where the `liveQueries` might be mutated. However, as soon as I remove the use of `startTransition`, when expiring the queries at a regular interval, the problem goes away. The component, `PresentationTool`, suddenly feels completely stable and nothing I do in the UI can provoke the infinite …
=> fix(presentation): remove use of startTransition

packages/visual-editing-helpers/src/createDataAttribute.test.ts, packages/visual-editing-helpers/src/createDataAttribute.ts, packages/visual-editing-helpers/src/types.ts, packages/visual-editing/src/create-data-attribute.ts, packages/visual-editing/src/index.ts, packages/visual-editing/src/next-pages-router/index.ts, packages/visual-editing/src/remix/index.ts
Improvements to help TS users avoid unexpected runtime errors when using `createDataAttribute`.
Draft as I can't figure out custom error messages for cases where `This expression is not callable` 😄
=> fix: improve createDataAttribute types

.github/renovate.json, .github/workflows/ci.yml
Note that enabling automerge in renovatebot doesn't allow it to bypass required status checks or code review. It uses the same automerge feature as in the GitHub PR web ui :)
It also updates the default CI workflow to run on `merge_group`, which is required to enable merge queues that have the same required status checks as regular merge rules.
=> refactor(ci): enable merge queues and automerge

apps/remix/app/root.tsx, apps/remix/app/routes/shoes.$slug.tsx, package.json, packages/visual-editing/README.md, pnpm-lock.yaml
After testing and merging https://github.com/sanity-io/visual-editing/pull/1216 I realised that it might be possible for the version that `sanity` and `@sanity/ui` is using to still be loaded in the studio.
This PR dedupes and overrides them all to use the same version, allowing us to test if bumping `framer-motion` causes any breaking behaviours in `sanity` and `@sanity/ui` in addition to `@sanity/presentation`.
This is important as those other packages uses this renovate rule: https://github.com/sanity-io/renovate-config/blob/2d752bc97fca2225a35299e6ab629f967b335195/studio-v3.json#L28
Other than that I've done some fixes in the Remix app to remove console warnings :)
=> chore: override `framer-motion` to a single version

packages/overlays/package.json, packages/svelte-loader/package.json, packages/visual-editing/src/ui/enableVisualEditing.tsx, packages/visual-editing/src/ui/renderVisualEditing.tsx
Improves lazy loading by shifting more code into the lazy loaded function itself.
[Before](https://esm.sh/@sanity/visual-editing@1.8.20?exports=enableVisualEditing):
```js
/* esm.sh - esbuild bundle(@sanity/visual-editing@1.8.20) es2022 production */
import{jsx as i,Fragment as m}from"/stable/react@18.3.1/es2022/jsx-runtime.js";var u="sanity-visual-editing",e=null,t=null,r=null;function a(l={}){r&&clearTimeout(r);let n=new AbortController;return Promise.all([import("/v135/react-dom@18.3.1/es2022/client.js"),import("/v135/@sanity/visual-editing@1.8.20/X-dHMvZW5hYmxlVmlzdWFsRWRpdGluZw/es2022/dist/_chunks-es/VisualEditing.js")]).then(([o,{VisualEditing:s}])=>{if(!n.signal.aborted){if(e||(e=document.createElement("div"),e.id=u,document.body.appendChild(e)),!t){let{createRoot:d}="default"in …
```
=> fix: improve lazy loading of `enableVisualEditing`

apps/astro/astro.config.mjs, apps/astro/package.json, apps/astro/src/components/visual-editing.astro, apps/astro/src/env.d.ts, apps/astro/src/layouts/layout.astro, apps/astro/src/load-query.ts, apps/astro/src/pages/shoes/[slug].astro, apps/astro/src/pages/shoes/index.astro, apps/astro/turbo.json, pnpm-lock.yaml
It's not much, but I think it's enough to get the ball rolling on visual editing in Astro.
All queries are now passed through a `loadQuery` function similar to the one found in the Next.js server-only example. Here, we set the proper config to support visual editing in case that env var is set to `'true'`. Similarly, a `<VisualEditing />` component is added to the root layout in order to toggle visual editing if enabled. The `<VisualEditing />` component just triggeres a full page refresh whenever a refresh should happen.
Some questions that pop up are:
- What is the best way to toggle visual editing in Astro? Is it an env var like we use here, or is there a better way a la `draftMode` in Next.js?
- How do you best encapsulate the `<VisualEditing />` component to make sure its script is …
=> feat(astro): add visual editing POC

packages/visual-editing/package.json, packages/visual-editing/svelte/VisualEditing.svelte
To allow formatting of `.svelte` and `.astro` files in the package.
=> chore(visual-editing): inherit root prettier config

packages/react-loader/package.json, packages/react-loader/src/jsx/SanityElement.tsx, packages/react-loader/src/jsx/jsx.tsx
The rewrite of `createElement` is to ensure we take full advantage of the JSX transform enhancements in React 19: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#new-jsx-transform-is-now-required
=> feat: support react 19

packages/presentation/src/preview/ShareUrlMenuItems.tsx
This should make the button also work in Firefox where ClipboardItem isn't implemented. The change keeps the ClipBoardItem working as before for iOS but relies on a promise that resolves to the text that should be copied in Firefox. This way both browsers work.
=> fix: add firefox support to "Copy URL" action

packages/presentation/src/editor/ContentEditor.tsx
Changes the "Main document" badge styling from this:
To this:
The styling loosely follows that of the "Latest" badge here, which doesn't itself use the `<Badge>` component.
=> refactor(presentation): restyle main document badge

packages/insert-menu/package.json, pnpm-lock.yaml
`sanity` was mistakenly added as a dependency instead of `@sanity/types`. Furthermore, `@sanity/types` needs to be defined as a peer dependency in order to avoid `Types of parameters 'schemaType' and 'schemaType' are incompatible.` errors when using this package inside the `sanity` monorepo.
=> fix(insert-menu): properly define @sanity/types dependency

packages/insert-menu/src/InsertMenu.tsx, packages/insert-menu/src/__workshop__/full.tsx
The insert menu is now a bit more resilient when it comes to toggling individual options or no options at all.
=> fix(insert-menu): remove border and extra spacing when there are no options

packages/presentation/src/i18n/resources.ts, packages/presentation/src/preview/PreviewFrame.tsx
I'm dropping this here for consideration but I've _slightly_ unconvinced myself because of the classic flip-flop button issue.
The PR combines the two viewport buttons into a single toggle. That means we only get to display one icon at a time.
When in desktop mode, do we show the desktop icon (current state) or the mobile icon (anticipated state on click)? Does it matter?
=> feat(presentation): combine viewport buttons into single toggle

packages/insert-menu/src/InsertMenu.tsx, packages/insert-menu/src/InsertMenuOptions.ts, packages/insert-menu/src/__workshop__/full.tsx
See each commit for details.
Most noticeable, I've allowed `previewImageUrl` to return `undefined`: d73ea505903b7016db7a8fb3e5b128ce872ac2e2
And allowed filtering to be enabled by default if there are more than 5 schema types in the menu: d5c2c82c746df714c64ebdebafb6bf1eb47b781f
=> fix(insert-menu): adjust `InsertMenuOptions` slightly

packages/insert-menu/src/InsertMenu.tsx
Fixes a typo in the `placement` property of the tooltip.
=> fix(insert-menu): set `placement` property of tooltip

packages/presentation/src/panels/PanelResizer.tsx, packages/presentation/src/preview/IFrame.tsx, packages/presentation/src/preview/PreviewFrame.tsx
We prevent users interacting with iframe content whilst the iframe is loading or whilst a connection is being established to  the Presentation tool.
Currently, this is done using `pointer-events: none;` on the iframe itself. However this means panel resizing does not play nicely at all (see Linear ticket for video), as I assume it prevents `mousemove` events as a user's cursor hovers over the iframe.
This PR attempts similar behaviour by replacing `pointer-events: none;` with a transparent absolutely positioned div, preventing interaction with the iframe but allowing the `mousemove` events we need to handle resizing.
Also some minor refactoring to tidy up the iframe component.
Drag the divider between iframe and document pane in Presentation tool on main and then this branch. Your …
=> fix(presentation): add iframe pointer events to prevent interference with resizing drag handler

packages/presentation/src/PresentationTool.tsx, packages/presentation/src/useMainDocument.ts, packages/presentation/src/useParams.ts
This one has been reported by a few different people.
Currently the main document resolver is far too keen in automatically navigating users to the main document for a given path:
A main document is resolved (or not) for the current preview path after each, and on the initial, navigation. This means that if a user follows a link which contains a path which resolves a main document, but a document id that does not match it, the main document will override that specified.
This PR fixes this by comparing the previous two router states (i.e. the previous navigation event) before forcing a main document navigation. If the previous navigation did not trigger a document change, or in other words the path changed but the document did not, then we can safely show the main document.
🔴 [Navigating …
=> fix(presentation): prevent displaying main document on explicit document navigation

packages/presentation/src/getIntentState.ts
This pull request addresses the handling of router state when navigating via intent links in the Presentation tool.
Currently, the Presentation tool does not maintain search parameter-specific state when handling intent links. This can lead to unintended side effects, such as resetting the preview URL and changing the viewport size when intent links are used to navigate within the tool.
The solution involves updating the `getIntentState` method to preserve the search parameters related to the Presentation tool's state (as defined in the [PresentationSearchParams](https://github.com/sanity-io/visual-editing/blob/main/packages/presentation/src/types.ts#L173-L177) interface), rather than requiring them to be explicitly defined when constructing an intent link.
In our test environment, we …
=> fix(presentation): preserve tool state across intent link navigations

packages/visual-editing/svelte/types.ts
Related to https://github.com/sanity-io/sanity-template-sveltekit-clean/issues/40.
Currently we import types from the sibling `/src` directory, which results in errors as `@repo/` imports cannot be resolved.
=> fix(visual-editing): import svelte types from dist over src

packages/visual-editing/src/controller.ts, packages/visual-editing/src/index.ts, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/elementsReducer.ts
This adds a method for updating an existing element detected by the overlay controller, rather than having to de-and-re-register it to track updates.
It also adds support for handling text mutations, which means changes in stega encoded strings will be picked up (they weren't before!)
It seems to make things much more predictable: no more randomly missing overlays!
=> fix(visual-editing): improve overlay mutation handling

apps/next-no-cache/next.config.mjs, apps/next-no-cache/tsconfig.json, apps/next-server-only/next.config.mjs, apps/next-server-only/tsconfig.json
They do use `canary` versions of `next`, so I've disabled their TypeScript checking for now, since it only seems to fail inside of `next` while regular `tsc --noEmit` works fine.
After this merges I'll re-enable the required vercel deployment checks for PRs for the repo.
=> chore: fix next builds

packages/visual-editing/turbo.json
We have to do a bit of a workaround in the project settings atm:
This PR lets us set it back to just `turbo run build-storybook` 🥳
=> chore: fix storybook build command

.gitignore, .vscode/extensions.json, .vscode/settings.json
The `settings.json` file ensures folks don't have to deal with making sure TypeScript loads correctly.
And the `extensions.json` will show a prompt in VS Code based editors:
I have a **_lot_** of extensions I like, but I wanted to make sure the recommendations are only the most useful ones, especially for the tooling we use in this monorepo:::
They are the kind of extensions that folks often don't know to look for, but are huge timesavers.
=> chore: improve vscode monorepo onboarding

apps/page-builder-demo/src/components/page/Page.tsx, apps/page-builder-demo/src/components/page/sections/FeatureHighlight.tsx, apps/page-builder-demo/src/components/page/sections/FeaturedProducts.tsx, apps/page-builder-demo/src/components/page/sections/Hero.tsx, apps/page-builder-demo/src/components/page/sections/Intro.tsx, apps/page-builder-demo/src/components/page/sections/Section.tsx, apps/page-builder-demo/src/components/page/types.ts, packages/visual-editing/src/controller.ts, packages/visual-editing/src/index.ts, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/OverlayDragInsertMarker.tsx, packages/visual-editing/src/ui/OverlayDragPreview.tsx, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/overlayStateReducer.ts, packages/visual-editing/src/util/drag-and-drop.md, packages/visual-editing/src/util/dragAndDrop.ts, packages/visual-editing/src/util/findSanityNodes.ts
**This PR:** 
- Implements "Drag Previews" for dragged elements. Drag previews render an abstract representation of the dragged element when possible, and default to a simple rectangle for small elements. 
- Adds the ability to opt in to drag and drop using the `data-sanity-draggable` HTML attribute.
- Improves drag insert position calculation, allowing for larger "hit" areas. 
- Adds an "Insert Marker" preview for drag sequences. This is a simple blue bar that appears on element top/bottom for vertical drag groups, or left/right for horizontal drag groups.
- Commits a simple `dnd.md` document to help provide insight into how drag and drop works. This can be refined over time, and help inform our actual documentation.
- Updates the Page Builder demo to allow `FeatureHighlight` to render …
=> feat(drag-and-drop): v0 UI

apps/studio/sanity.cli.ts
This speeds up `styled-components` for `sanity dev` when running the visual editing test studio locally on http://localhost:3333.
More info https://github.com/sanity-io/sanity/pull/7440
=> chore: speedup `sanity dev`

apps/page-builder-demo/src/components/page/sections/FeatureHighlight.tsx, apps/page-builder-demo/src/components/page/sections/FeaturedProducts.tsx, apps/page-builder-demo/src/components/page/sections/Hero.tsx, apps/page-builder-demo/src/components/page/sections/Intro.tsx, apps/page-builder-demo/src/components/page/sections/Section.tsx, packages/visual-editing/src/controller.ts, packages/visual-editing/src/util/drag-and-drop.md, packages/visual-editing/src/util/findSanityNodes.ts
This PR updates the Drag and Drop API to be opt-out. 
It also simplifies the functionality, enabling drag-and-drop only on elements with an array path.
=> chore(drag-and-drop-opt-out)

.github/workflows/release-canary.yml, package.json, pnpm-lock.yaml, scripts/release-canary.mjs
Automation for publishing canaries on the `canary` branch. 
Can be run using the "Run workflow" button here https://github.com/sanity-io/visual-editing/actions/workflows/release-canary.yml (the button won't show up until after this PR is merged to main), once this workflow is synced to the `canary` branch.
The workflow itself will always use the `canary` branch, to avoid mistakes. You can also run `pnpm release:canary` locally, if you have publishing rights in our npm org.
I've tested the workflow on this branch, here's the commit it pushed: https://github.com/sanity-io/visual-editing/commit/a3b1834d741d44f024cc379f53a42c833809fd8e
The packages it published has provenance, and resolved dependencies correctly: https://www.npmjs.com/package/@sanity/react-loader/v/1.10.6-canary.3 (you can …
=> chore: add canary release workflow

apps/studio/.env.local
Helps the maintainer burden until we properly support origin patterns and array of strings for `presentationTool({previewUrl: {origin: ['*.sanity.dev', '*.sanity.build']}})`
=> chore: create env var template for test studio

packages/svelte-loader/package.json
Adds missing `svelte` specific export condition
=> fix(svelte-loader): add svelte export condition

packages/presentation/src/PresentationTool.tsx, packages/presentation/src/editor/PostMessagePreviewSnapshots.tsx
This should fix missing document labels on overlay elements corresponding to documents without draft versions when in the draft perspective.
=> fix(presentation): observe correct preview snapshot perspectives

packages/visual-editing/src/ui/context-menu/contextMenuItems.ts, packages/visual-editing/src/util/mutations.ts
Adds a duplicate action to the context menu for array items. Also refactors to use `doc.patch` where applicable.
=> feat(visual-editing): add duplicate context menu action

packages/next-loader/src/defineLive.tsx, packages/presentation/src/PresentationToolGrantsCheck.tsx, packages/presentation/src/i18n/resources.ts, packages/preview-url-secret/README.md, packages/preview-url-secret/src/createClientWithConfig.ts, packages/preview-url-secret/src/createPreviewSecret.ts, packages/preview-url-secret/src/types.ts
We used to require Editor or above to allow someone to use Presentation Tool when `previewUrl.previewMode.enable` was used, as it creates documents in your dataset with secrets, and used to have a `sanity-preview-url-secret.**` document `_id` prefix.
The `sanity-preview-url-secret.` prefix ensures the documents can't be queried without being Viewer or above. But the downside is that Collaborator roles can only create `drafts.` prefixes.
By moving to `drafts.` Collaborators can now use Presentation Tool 🥳 
Enterprise customers can with custom roles setup access for Viewer roles as well. We always supported this, but didn't document how to set it up. I've updated the README with a step-by-step for how to use it.
Viewers and below also now see a toast message when they can't create preview …
=> feat: lower permissions req to Collaborator

packages/preview-url-secret/src/parsePreviewUrl.test.ts, packages/preview-url-secret/src/parsePreviewUrl.ts, packages/preview-url-secret/src/types.ts, packages/preview-url-secret/src/validatePreviewUrl.ts
Adds `studioPreviewPerspective` to the `validatePreviewUrl` handler.
This will be used by `next-sanity` to support the perspective switcher:
We currently only pick up on what perspective the studio is using after domReady, when `@sanity/comlink` is connected and presentation tool tells `@sanity/next-loader` what the perspective is.
This leads to the unfortunate scenario:
1. Presentation Tool is open and has perspective set to `Published`.
2. A new vercel deployment happened, and draft mode is now disabled automatically, leading to the connection lost error over preview iframe. The Studio search params has `&perspective=published` in the URL.
3. The user does a full page reload to reset, since `&perspective=published` is in the URL then the iframe has …
=> feat(validatePreviewUrl): add studioPreviewPerspective

packages/@repo/sanity-schema/src/page-builder-demo/index.tsx, packages/presentation/src/overlays/schema/extract.ts
This one is a [bit tricky to reproduce on this repo](https://github.com/sanity-io/visual-editing/pull/2002/commits/8968474aaa1395caece33a03f6553631f4dd50ec), since it's also breaking `sanity schema extract` which we use for TypeGen:
```
name: 'media',
// @ts-expect-error this is actually allowed at runtime
title: <>Media</>,
```
Having JSX in a `title` anywhere in the schema will cause a crash that causes the comlink connection to be lost:
It's currently happening if you go to the [Test Studio](https://test-studio.sanity.dev/presentation/presentation/simpleBlock/eed1de44-4731-48f5-ab77-ea50a82dfef9?preview=%2Fpreview%2Findex.html) over at the `sanity` monorepo.
=> fix(schema-extract): handle `title` sometimes being a React node

packages/core-loader/README.md, packages/next-loader/README.md, packages/react-loader/README.md, packages/svelte-loader/README.md, packages/visual-editing-helpers/src/comlinkCompatibility.ts, packages/visual-editing/README.md
After a lot of debugging I noticed that every time `@sanity/presentation@1.16.5` sent a `channel/heartbeat` like this:
```json
{
"connectionId": "46d4c484-df9c-4c7f-b633-d1739330567e",
"domain": "sanity/channels",
"from": "presentation",
"id": "b9cf5be9-e64e-4efb-812b-4ace7c98c857",
"to": "overlays",
"type": "channel/heartbeat"
}
```
The connection was lost.
Comparing payloads and versions, `@sanity/visual-editing@2.1.0` responds with:
```json
{
"connectionId": "46d4c484-df9c-4c7f-b633-d1739330567e",
"data": {
"responseTo": "b9cf5be9-e64e-4efb-812b-4ace7c98c857"
},
"domain": "sanity/channels",
"from": "overlays",
"id": "b19f2420-e0d2-4156-9d36-982162129df2",
"to": "presentation",
"type": "channel/response"
}
```
And all is well.
While `@sanity/visual-editing@2.2.0` responds with:
```json …
```
=> fix(comlink): handle heartbeat compatibility correctly

apps/next-with-i18n/app/(website)/[locale]/[...path]/page.tsx, apps/next-with-i18n/app/(website)/[locale]/layout.tsx, apps/next-with-i18n/app/(website)/[locale]/page.tsx, apps/next-with-i18n/app/api/disable-draft/route.ts, apps/next-with-i18n/app/api/draft/route.ts, apps/next-with-i18n/data/sanity/loadQuery.ts, apps/next/src/app/api/draft-mode/disable/route.ts, apps/next/src/app/compat/layout.tsx, apps/next/src/app/compat/page.tsx, apps/next/src/app/only-visual-editing/layout.tsx, apps/next/src/app/only-visual-editing/page.tsx, apps/next/src/app/shoes/[slug]/page.tsx, apps/next/src/app/shoes/layout.tsx, apps/next/src/app/shoes/page.tsx, apps/next/src/app/shoes/sanity.ssr.ts, apps/page-builder-demo/src/app/layout.tsx, apps/page-builder-demo/src/app/pages/[slug]/page.tsx, apps/page-builder-demo/src/app/product/[slug]/page.tsx, apps/page-builder-demo/src/app/project/[slug]/page.tsx, packages/core-loader/package.json, packages/preview-kit-compat/package.json, packages/visual-editing-helpers/package.json, packages/visual-editing/package.config.ts, packages/visual-editing/package.json, pnpm-lock.yaml
We've had some massive bundle bloat due to accidental inlining:
- https://bundlephobia.com/package/@sanity/preview-kit-compat@1.5.9 vs https://bundlephobia.com/package/@sanity/preview-kit-compat@1.5.7
- https://bundlephobia.com/package/@sanity/visual-editing@2.2.1 vs https://bundlephobia.com/package/@sanity/visual-editing@2.1.10
=> fix: stop inlining rxjs and `@sanity/comlink`

packages/next-loader/src/client-components/live/SanityLive.tsx, packages/next-loader/src/defineLive.tsx
The browser token warning in `@sanity/client` is confusing in userland:
```
You have configured Sanity client to use a token in the browser. This may cause unintentional security issues. See https://www.sanity.io/help/js-client-browser-token for more information and how to hide this warning.
```
As setting `browserToken` in `defineLive` does exactly what it implies, setting a token for the browser. The warning itself isn't actionable and thus it's removed here.
=> fix: remove unnecessary warning

apps/page-builder-demo/src/app/dnd/page.tsx, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/util/dragAndDrop.ts, packages/visual-editing/src/util/findSanityNodes.ts
- Fixes a bug where certain `overflow` and `height` values on the document root allow scrolling while the minimap is open 
- Only enables drag and drop where `data-sanity` attribution is explicitly applied. Right now we have some issues mutating primitive arrays, and it feels generally safer (and in line with the docs) to require this.
=> chore(drag-and-drop): minimap stability, drag enablement

packages/presentation/src/PostMessagePerspective.tsx, packages/presentation/src/PresentationTool.tsx, packages/presentation/src/features/PostMessageFeatures.tsx, packages/presentation/src/overlays/PostMessageDocuments.tsx, packages/presentation/src/overlays/schema/PostMessageSchema.tsx, packages/visual-editing-helpers/src/types/comlink.ts, packages/visual-editing/src/controller.ts, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/History.tsx, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/VisualEditing.tsx, packages/visual-editing/src/ui/optimistic-state/machines/createSharedListener.ts, packages/visual-editing/src/ui/optimistic-state/useOptimisticActor.ts, packages/visual-editing/src/ui/schema/SchemaProvider.tsx, packages/visual-editing/src/ui/useController.tsx, packages/visual-editing/src/ui/usePerspectiveSync.tsx, packages/visual-editing/src/ui/useReportDocuments.ts
This PR contains quite a few fixes related to features recently merged into `main` from `canary`. LMK if you'd like these to be split into separate PRs! I'd recommend reviewing each commit in turn if not.
Key commits explained below:
Fixes a bug reported earlier today where trying to resolve an inline array item field from the schema would throw an error. High importance as hovering over overlay elements now triggers field resolution, so if an overlay's path points to an inline array item, an uncaught error is thrown.
Previously new comlink targets for popups were added by using the `.size` of a Set stored as state as a `useEffect` dependency, but `.add()` was being called directly, rather than the `Set` being replaced using `setState`, which I believe failed to trigger the `useEffect`. …
=> fix: resolve issues with newly added canary features

packages/comlink/src/node.ts, packages/comlink/src/request.ts, packages/comlink/src/types.ts, packages/visual-editing/src/ui/VisualEditing.tsx, packages/visual-editing/src/ui/optimistic-state/machines/createSharedListener.ts, packages/visual-editing/src/ui/schema/SchemaProvider.tsx, packages/visual-editing/src/ui/usePerspectiveSync.tsx
This adds a new warning message about package version mismatching when visual editing doesn't receive a response to a features request. This replaces all the individual warnings emitted by other requests used to support new features (e.g. fetching the schema) when these are not supported by the user's Presentation version.
=> feat(visual-editing): add package version mismatch warning

apps/live-next/app/alert-banner.tsx, apps/live-next/app/draft-mode-status.tsx, apps/live-next/app/layout.tsx, apps/live-next/package.json, packages/next-loader/src/client-components/live/SanityLive.tsx, packages/next-loader/src/hooks/context.ts, packages/next-loader/src/hooks/index.ts, packages/next-loader/src/hooks/useIsLivePreview.ts, packages/next-loader/src/hooks/useIsPresentationTool.ts
The new hooks are higher level, and tailored to the use cases I've found is needed in most templates:
1. I want to show a UI warning that the app is in draft mode when outside of Presentation Tool, so editors don't freak out and think they've accidentally published some content.
3. In production it's awesome to show a "A new post is available" toast with a refresh button so that my visitors can consume my content in peace and decide when to see the new content. In live preview however I don't want my editors to constantly hit a refresh button toast every time they make a draft edit before they can see it.
I want to only show a Draft Mode message if I'm not in the Presentation Tool:
```tsx
"use client";
import { useIsPresentationTool } from "next-sanity/hooks";
import { useEffect } from …
```
=> feat: add `useIsLivePreview` & `useIsPresentationTool` hooks

packages/visual-editing-helpers/src/urlStringToPath.test.ts, packages/visual-editing-helpers/src/urlStringToPath.ts, packages/visual-editing/package.json, packages/visual-editing/src/ui/context-menu/contextMenuItems.ts, packages/visual-editing/src/ui/schema/SchemaProvider.tsx, packages/visual-editing/src/util/mutations.ts, packages/visual-editing/src/util/randomKey.ts, pnpm-lock.yaml
This PR contains fixes for resolving field paths containing references to nested unions in the parsed schema.
It also broadens the regexes used to convert URL strings to paths, and adds tests to cover various formats.
To be extra careful, I've replaced the `generateKey` function with the `randomKey` function used in the `sanity` monorepo (relies on the `get-random-values-esm` dependency). This is so that we are no longer generating uuid keys when performing mutations that add array items. The hyphens were seemingly problematic, hence the need for improving the regexes.
=> fix(visual-editing): nested union schema field resolution

apps/page-builder-demo/src/components/page/Page.tsx, packages/visual-editing/src/ui/optimistic-state/useOptimistic.ts
There are likely scenarios where you would want to use `useOptimistic` with a nullable passthrough value. For example when rendering a page with an optionally empty value.
This PR just removes the nullable `lastPassthrough` check. I'm sure it was there for good reason, but I haven't been able to find a situation where removing it causes issues so far.
@stipsan assigning you to this as you wrote it originally and probably have a good idea of why that check exists.
=> fix(visual-editing): remove useOptimistic nullable check

packages/visual-editing/src/ui/context-menu/ContextMenu.tsx, packages/visual-editing/src/ui/context-menu/contextMenuItems.ts
PR has two small fixes:
- Fixes a bug that prevented the context menu's insert after action from working.
- Correctly dismisses the context menu after clicking an action.
=> fix(visual-editing): correct insert after action, add dismiss

.github/workflows/release-corel.yml, scripts/release-corel.mjs
adds release scripts for `corel`
Using `corel` tag as it matches with the tag we have in `sanity`
=> chore: set release scripts for corel

packages/visual-editing-helpers/src/comlinkCompatibility.ts
- Handshake messages in the internal `@sanity/channels` package sent the connection ID as the value of `data.id`.
- Comlink handshakes don't, and instead just check against the `connectionId` property.
- `data.id` isn't currently set in the comlink to channel compatibility transform.
- So handshakes currently fail when a newer version of `@sanity/presentation` is trying to communicate with an older version of `@sanity/visual-editing`.
- This PR adds the necessary `data.id` value in the compatibility transform.
=> fix: backwards compatible handshake payloads

packages/presentation/src/editor/PostMessagePreviewSnapshots.tsx, packages/visual-editing-helpers/src/types/comlink.ts, packages/visual-editing/src/ui/preview/PreviewSnapshotsContext.tsx
Fix for https://github.com/sanity-io/sanity/issues/7689. Removes the (unused) media value from preview snapshot payloads.
=> fix(presentation): remove media from preview snapshot payload

packages/visual-editing/src/controller.ts
It looks like elements are  currently activated (i.e. become visible) on registration (i.e. when they are detected in the DOM), even if the controller itself is deactivated (i.e. the Edit button is in the "Off" state). So for example navigating between pages in an app with Edit set to "Off" will result in overlays being rendered.
This PR adds a simple check to prevent that.
=> fix(visual-editing): prevent always activating elements on registration

packages/visual-editing/package.json, pnpm-lock.yaml
Relates to #2113, by bumping `@sanity/mutate` the package `nanoid` is inlined:
- https://github.com/sanity-io/mutate/commit/67e46b615148c0bf772743aca3e038e0d752f64c
The reason why we inline it, is due to how `nanoid` targets envs in its bundling. [By default it imports `webcrypto` from `node:crypto`](https://github.com/ai/nanoid/blob/55cd90d7f90d4ffedbeff4734a5d0d9abfec0aca/index.js#L1), and this is the import that Shopify Hydrogen doesn't like.
[It support browser environments with a separate export](https://github.com/ai/nanoid/blob/55cd90d7f90d4ffedbeff4734a5d0d9abfec0aca/index.browser.js), however [it only uses the `browser` export condition.](https://github.com/ai/nanoid/blob/55cd90d7f90d4ffedbeff4734a5d0d9abfec0aca/package.json#L34)
Shopify Hydrogen is setup by default to deploy to …
=> fix: resolve `node:crypto` error on Shopify Hydrogen

packages/preview-url-secret/README.md
We experienced some parsing issues when rendering this file on the docs site. Unless there are specific stylistic needs, it's preferable to use markdown's built-in image syntax rather than html in readme files for better compatibility.
=> fix(docs): update img tags to markdown format

apps/page-builder-demo/src/components/overlays/OverlayHighlight.tsx, apps/page-builder-demo/src/components/overlays/resolver.ts, apps/studio/presentation/CustomHeader.tsx, apps/studio/sanity.config.ts, packages/presentation/src/PresentationTool.tsx, packages/presentation/src/index.ts, packages/presentation/src/overlays/SharedStateContext.tsx, packages/presentation/src/overlays/SharedStateProvider.tsx, packages/presentation/src/overlays/useSharedState.ts, packages/presentation/src/preview/PreviewHeader.tsx, packages/presentation/src/types.ts, packages/visual-editing-helpers/src/types/comlink.ts, packages/visual-editing/src/index.ts, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/shared-state/SharedStateContext.ts, packages/visual-editing/src/ui/shared-state/SharedStateProvider.tsx, packages/visual-editing/src/ui/shared-state/sharedStateStore.ts, packages/visual-editing/src/ui/shared-state/useSharedState.ts
This one relies on #2117 (will fix the `visual-editing-page-builder-demo` deployment), and #2118 to allow mounting a component which can demonstrate how shared state is used.
I'll write more comprehensive documentation, but the TL;DR of it is:
In Presentation, you can share state by passing a key and value using the `useSharedState` hook:
```ts
import {useShatedState} from '@sanity/presentation'
const [enabled, setEnabled] = useState(false)
useSharedState('overlay-enabled', enabled)
```
Then, in your app, you can define a custom overlay component which uses an identically named hook (is this sensible?) which accepts just a single param—the key—and returns the shared value:
```ts
import {useShatedState} from '@sanity/visual-editing'
const enabled = useSharedState('overlay-enabled')
``` …
=> feat: add shared state

packages/presentation/src/overlays/useSharedState.ts
Removes the unnecessary removal of shared state values when the component using `useSharedState` unmounts.
=> fix(presentation): remove shared state value removal on unmount

apps/page-builder-demo/src/components/overlays/ExcitingTitleControl.tsx, apps/page-builder-demo/src/components/overlays/resolver.tsx, packages/visual-editing/src/index.ts, packages/visual-editing/src/next-pages-router/index.ts, packages/visual-editing/src/overlay-components/components/PointerEvents.tsx, packages/visual-editing/src/overlay-components/index.ts, packages/visual-editing/src/react/index.ts, packages/visual-editing/src/remix/index.ts, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/ElementOverlay.tsx
Passes additional values in the overlay component resolver context object and the props passed to overlay components.
Specifically the schema types for the given field and that field's document (alongside the existing field's parent schema type) have been added to context, and the props now extend that context with the additional `PointerEvents` helper component.
Added some comments in the context type to better clarify what value is what.
Also adds the ability to return a `ReactElement` directly from the resolver function.
=> feat(visual-editing): simplify overlay component context and props

packages/visual-editing/src/overlay-components/defineOverlayComponents.ts, packages/visual-editing/src/overlay-components/index.ts
Adds a helper function to allow creating overlay component resolvers using a helper function:
```ts
const components = defineOverlayComponents((context) => {
return defineOverlayComponent(SomeComponent, props)
})
```
Rather than mixing a type and fn for individual component definitions:
```ts
const components: OverlayComponentResolver = (context) => {
return defineOverlayComponent(SomeComponent, props)
}
```
=> feat(visual-editing): add `defineOverlayComponents` helper function

packages/presentation/src/PresentationTool.tsx
Attempted fix for the unnecessary refresh issue users are reporting, e.g. https://github.com/sanity-io/visual-editing/issues/2087
Turns out Presentation's comlink controller was being reinitialised each time the iframe state changed due to an incorrect `useEffect` dependency.
=> fix(presentation): prevent controller reinit on iframe status change

packages/comlink/src/constants.ts, packages/comlink/src/controller.ts, packages/comlink/src/node.ts, packages/comlink/src/request.ts, packages/comlink/src/types.ts
Currently, comlink's node state machine will only handle syn handshake events when in an `idle` state. In some situations, the controller or some of the channels it maintains may detect a loss of connection and transition to a `handshaking` state, the disconnect event emitted at this point may then fail to reach the relevant node(s), and thus the node will remain in a `connected` state, as the nodes themselves only blindly respond to heartbeat events.
This PR adds a change so that the node state machine will _always_ transition to its internal `handshaking` state when receiving a syn handshake event, regardless of the state it is currently in. This should greatly improve the success rate of attempt reconnects. For example you may have noticed in our test environments that the connection …
=> fix(comlink): ensure nodes always accept handshake synchronize events

apps/page-builder-demo/src/components/overlays/ExcitingTitleControl.tsx, apps/page-builder-demo/src/components/page/DnDCustomBehaviour.tsx, apps/remix/app/CustomControlsComponent.tsx, packages/visual-editing/src/index.ts, packages/visual-editing/src/ui/comlink/index.ts, packages/visual-editing/src/ui/context-menu/ContextMenu.tsx, packages/visual-editing/src/ui/context-menu/contextMenuItems.tsx, packages/visual-editing/src/ui/optimistic-state/index.ts, packages/visual-editing/src/ui/optimistic-state/machines/createSharedListener.ts, packages/visual-editing/src/ui/optimistic-state/machines/datasetMutatorMachine.ts, packages/visual-editing/src/ui/optimistic-state/useDocuments.ts, packages/visual-editing/src/util/mutations.ts, packages/visual-editing/src/util/useDragEvents.ts
This is kind of a fix dressed up as a feat.
Accessing optimistic document snapshots is currently error prone as it is assumed the snapshot will be available, in actual fact it may not be as snapshots have to be fetched from Content Lake via Presentation tool. In most situations this is fine as user interaction is required to trigger some document snapshot getter and so will _likely_ not occur immediately
`doc.get()` returns a snapshot and throws if the snapshot is unavailable. This is now deprecated.
`doc.getSnapshot()` replaces it. It returns a promise which is resolved when the snapshot is actually returned.
As a result the Context Menu now has a loading state (video below demonstrates this with an artificial 5s delay added to snapshot fetching), and interactions like drag and drop will …
=> feat(visual-editing): add async getSnapshot to optimistic documents

apps/page-builder-demo/src/components/page/sections/Hero.tsx, packages/visual-editing/src/controller.ts, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/Overlays.tsx
Fix for #2179. This unsets the cursor style when `mouseleave`-ing an overlay element.  Previously on `mouseleave` the element was specified as the `hoveredElement`, which I think would be the element that the cursor was entering after leaving the one we want to reset?
Two questions:
1. Should we only set cursor to `auto` on child elements of drag groups?
2. As this manipulates the DOM outside of our visual editing element, should we store and revert to any user set cursor style value?
@georgedoescode I've assigned this to you as you'll know the original intention!
=> fix(visual-editing): unset overlay applied cursor on mouseleave

apps/page-builder-demo/src/sanity.types.ts, packages/presentation/src/preview/IFrame.tsx, packages/presentation/src/preview/Preview.tsx, packages/presentation/src/preview/PreviewHeader.tsx
Whenever the preview is showing a layout that isn't super simple the viewport transition is quite janky and jarring:
https://github.com/user-attachments/assets/c11f4d32-7b9c-4199-89f8-2cef21658f4f
By moving it to CSS View Transitions instead of having Framer Motion animate the `<iframe>` `width` and `height` it's much smoother:
https://github.com/user-attachments/assets/def0e72b-360a-4649-b65f-fe374c196ff2
=> fix: use CSS view transition for viewport iframe toggling

packages/comlink/src/connection.ts, packages/comlink/src/controller.ts, packages/comlink/src/node.ts
Small fix for comlink that improves the types for `post` and `fetch` methods.
Previously, I added functionality to make the second/data param optional so that:
```ts
// Given a message type without data
type MsgWithoutData = {
type: 'some-message-without-data'
data: undefined
}
// You can call 
node.post('some-message-without-data')
// Instead of having to always explicitly pass two params
node.post('some-message-without-data', undefined)
```
But this has the unintended side effect that:
```ts
// Given a message type with data
type MsgWithData = {
type: 'some-message-with-data'
data: { foo: string }
}
// You could call this without an error
node.post('some-message-with-data')
```
These changes mean the second parameter is now required if the type's `data` param is not undefined
```ts
// …
```
=> fix(comlink): require data param if defined on post and fetch methods

.github/workflows/release-please.yml
Release Please provides two types of release outputs, depending on the type of repository setup:
- **Single-package repositories**: If you publish the root `package.json` (i.e., the `.` in Release Please), the action outputs `release_created` (singular).
- **Monorepositories**: If you publish sub-packages rather than the root, the action outputs `releases_created` (plural).  
For more details, refer to the [Release Please Action documentation](https://github.com/googleapis/release-please-action?tab=readme-ov-file#outputs).
---
In the current version, it tries to compare `'false' || github['event']['inputs']['publish'] == 'true'`, which returns `'false'` as a string, always making this expression truthy.
---
This PR adjusts the logic to correctly handle outputs, ensuring the action behaves …
=> fix(ci): fixes release-please workflow conditional

packages/comlink/src/node.ts, packages/core-loader/src/live-mode/enableLiveMode.ts, packages/presentation/src/PresentationTool.tsx, packages/preview-kit-compat/src/useDocumentsInUse.ts, packages/visual-editing/src/ui/VisualEditing.tsx, packages/visual-editing/src/ui/useComlink.tsx, packages/visual-editing/src/ui/useDatasetMutator.ts
Follows up on #2308, turns out the root cause is a race condition that happens on fast machines and optimal race conditions. Where `<VisualEditing />` winds up sending `await comlink.fetch` before `<PresentationTool />` has had time to mount relevant `PostMessage` components, and run their `useEffect`'s that sets up `comlink.on()` handlers on the other side.
See the https://github.com/sanity-io/visual-editing/compare/debug branch for examples, in the test studio: https://visual-editing-studio-git-debug.sanity.dev/page-builder-demo/presentation/dndTestPage/60a2a9dd-7514-4b3c-8a2a-af06fb4cc31e?preview=/dnd
The short term fix is to delay a bit when the comlink is set in `<VisualEditing />` hoping its setup by then. The real long term fix is to refactor `<PresentationTool />` itself to use a …
=> fix: improve race condition connectivity handling

packages/visual-editing/src/constants.ts, packages/visual-editing/src/ui/VisualEditing.tsx, packages/visual-editing/src/ui/renderVisualEditing.tsx, packages/visual-editing/src/util/findSanityNodes.ts
Allows us to remove this logic from libraries like `next-sanity` https://github.com/sanity-io/next-sanity/blob/5aa90df441f4b6f8070ea36645ffe5c19a2925b3/packages/next-sanity/src/visual-editing/client-component/VisualEditing.tsx#L134-L151
=> fix: make `<VisualEditing>` render in portals consistently

packages/presentation/src/plugin.tsx
Adds the `__internalApplicationType` property to the configuration of the presentation tool as part of the CoreUI project. More information can be seen here – https://github.com/sanity-io/sanity/pull/7980 – we added this parameter to many of the common tools sanity provides.
TLDR; this helps us identify & group tools across studio manifests to be used for the CoreUI menus etc. We see it as a temporary measure of using a studio manifest (similar to create) and this will be replaced in the ✨ _future_ ✨.
=> feat(presentation): add __internalApplicationType to tool spec

apps/studio/package.json, apps/studio/turbo.json, packages/visual-editing/src/controller.ts, packages/visual-editing/src/react/useDocuments.ts, packages/visual-editing/src/stories/Overlays.stories.tsx, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/ElementOverlay.tsx, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/VisualEditing.tsx, packages/visual-editing/src/ui/useController.tsx, pnpm-lock.yaml
[Thread](https://sanity-io.slack.com/archives/C043ZRB9E4S/p1736263845340979)
It's clear we now need to make a distinction on wether we're inside an iframe, or a popup window, as the UX have nuanced differences.
iframes don't want "Open in Studio" buttons for example, but popups do 😅 
Also fixes a regression from https://github.com/sanity-io/visual-editing/pull/2356
=> fix: support overlay clicks in popups

packages/visual-editing/svelte/VisualEditing.svelte, packages/visual-editing/svelte/hooks.ts, packages/visual-editing/svelte/optimistic/useOptimistic.ts, packages/visual-editing/svelte/types.ts
The new optimistic functionality introduced imports from an internal repo (`@repo/visual-editing-helpers`) that `svelte-package` is unable to bundle. This moves the `getPublishedId` function inline instead of importing for now as it's super simple.
Should fix https://github.com/sanity-io/visual-editing/issues/2333.
=> fix(visual-editing): fix svelte imports

apps/svelte/src/hooks.server.ts, apps/svelte/src/routes/shoes-with-loaders/+layout.svelte, apps/svelte/src/routes/shoes/+layout.svelte, packages/svelte-loader/package.json, packages/svelte-loader/src/hooks.ts, packages/visual-editing/svelte/hooks.ts, packages/visual-editing/svelte/types.ts, pnpm-lock.yaml
The Svelte specific preview mode functionality we've implemented in the visual editing package imports `redirect` from `@sveltejs/kit`. However if the consuming app is using mismatched dependency versions the redirect will fail. See https://github.com/sveltejs/kit/issues/11749#issuecomment-1966565367 for more details as to why.
The PR just adds the option to pass a `redirect` function explicitly to override that imported by the package itself, which should ensure that preview mode redirects to the correct location instead of throwing an error.
=> feat: add optional redirect override to svelte preview handler

packages/presentation/src/fieldActions/openInStructure.ts, pnpm-lock.yaml
Hey Sanity team! 👋
On some of our projects, the Presentation tool is the only tool used to work with content; i.e. there's no Structure tool at all.
In this scenario, the "Open in Structure" action will end up linking back to the Presentation tool itself, so nothing happens when you click on it.
Example screenshot below. Our Presentation tool is titled "Live Edit" and the action says "Open in Live Edit", but that tool is already open so the button effectively does nothing.
This PR solves that by excluding the Presentation tool when trying to find matches in `findStructureTool`. With this change, there's no action button shown at all, since there's no relevant tool to link to:
=> fix(presentation): prevent openInStructure from linking to the presentation tool itself

packages/presentation/src/editor/PostMessagePreviewSnapshots.tsx, packages/visual-editing-helpers/src/types/comlink.ts, packages/visual-editing/src/ui/preview/PreviewSnapshotsProvider.tsx
Ensure the visual editing package explicitly requests preview snapshots for Presentation on connect, this should fix the issue we're seeing with Astro.
Currently snapshots are only returned from Presentation when the preview snapshot observable emits. This is a problem if for example the app inside the iframe reloads, as the observable will not emit until some change is made.
=> fix: explicitly fetch preview snapshots on connect

apps/page-builder-demo/src/sanity.types.ts, packages/visual-editing/src/overlay-components/components/UnionInsertMenuOverlay.tsx, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/context-menu/ContextMenu.tsx, packages/visual-editing/src/ui/context-menu/contextMenuItems.tsx, packages/visual-editing/src/ui/telemetry/TelemetryContext.tsx, packages/visual-editing/src/ui/telemetry/TelemetryProvider.tsx, packages/visual-editing/src/ui/telemetry/useTelemetry.tsx, packages/visual-editing/src/util/dragAndDrop.ts
This PR: 
- Adds a new `useTelemetry` hook to Visual Editing that makes it easier to send telemetry in nested components
- Adds several new telemetry events: 
- `Visual Editing Drag Minimap Enabled`
- `Visual Editing Context Menu Item Removed`
- `Visual Editing Context Menu Item Duplicated`
- `Visual Editing Context Menu Item Moved`
- `Visual Editing Context Menu Item Inserted`
- `Visual Editing Insert Menu Item Inserted`
- `Visual Editing Overlay Clicked`
Question for @sanity-io/creator-x — is there any other events we would like to add as part of this PR? Trying to hit all the basic elements here and we can expand with more niche scenarios in time. 
⚠️ Events must be reviewed by @sanity-io/data-eng  before merging ⚠️
=> chore: add extended telemetry, useTelemetry hook

packages/core-loader/test/encodeDataAttribute.test.ts, packages/visual-editing-csm/src/createDataAttribute.test.ts, packages/visual-editing-csm/src/decodeSanityNodeData.ts, packages/visual-editing-csm/src/encodeSanityNodeData.ts, packages/visual-editing-csm/src/sanityNodeSchema.ts, packages/visual-editing-types/src/index.ts, packages/visual-editing/src/ui/useReportDocuments.ts
Since https://github.com/sanity-io/sanity/pull/8320 landed it's no longer necessary to send a draft id in the `visual-editing/documents` postMessage handler
=> fix: remove isDraft

packages/next-loader/src/defineLive.tsx
It's no longer necessary to use vX with Draft Live Content 🥳
=> fix: remove vX override

packages/core-loader/src/live-mode/enableLiveMode.ts, packages/next-loader/src/client-components/live-stream/SanityLiveStream.tsx
Increasing the interval reduces the gc work Presentation has to do when keeping track of queries. Especially when moving back and forth between URLs.
=> fix: increase heartbeat interval from 1s to 10s

packages/visual-editing/src/ui/Overlays.tsx
It looks like https://github.com/sanity-io/visual-editing/commit/74fdcddacb7ef02748cf729b67c6cdbb4c3647e2 introduced some changes in the `DocumentReporter` component which removed the unique document ID check.
This is causing documents to be unobserved/observed on every render—such as hovering on/off overlay—even if the IDs haven't changed, which in turn triggers a request to Presentation to fetch new document snapshots for every document on the page. This can result in hundreds of requests on each interaction. See video below.
This PR reverts that change, and should fix this issue.
https://github.com/user-attachments/assets/71fe6447-99b7-4ee9-91b9-bf62152b0583
=> fix(visual-editing): prevent snapshot overfetching

apps/page-builder-demo/src/sanity.types.ts, packages/visual-editing/package.json, packages/visual-editing/src/stories/Overlays.stories.tsx, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/VisualEditing.tsx, packages/visual-editing/src/ui/useComlink.tsx, packages/visual-editing/src/ui/useDatasetMutator.ts, pnpm-lock.yaml
I've tried to screencap the before/after of this one, but it's notoriously difficult. The bug manifests itself as `status` in `<Overlays />` being stuck as `idle`, thus overlay elements never render: https://github.com/sanity-io/visual-editing/blob/d0702d8b5264d287bfcc751bbb6e02a553567fb2/packages/visual-editing/src/ui/Overlays.tsx#L347
With the latest stable of `@sanity/visual-editing` I can reproduce it after 10 or so attempts of rapidly switching between structure tool and presentation tool.
With `@sanity/visual-editing@2.12.15-canary.0` I've attempted to reproduce almost 100 times and it no longer happens 😮‍💨
=> fix: solve race in comlink.onStatus

apps/astro/src/load-query.ts, apps/next-with-i18n/data/sanity/loadQuery.ts, apps/next/src/app/only-visual-editing/page.tsx, apps/next/src/app/shoes/[slug]/page.tsx, apps/next/src/app/shoes/page.tsx, apps/next/src/app/shoes/sanity.ssr.ts, apps/next/src/pages/pages-router/performance-test/index.tsx, apps/next/src/pages/pages-router/shoes/[slug].tsx, apps/next/src/pages/pages-router/shoes/index.tsx, packages/@repo/sanity-schema/src/shoes/index.tsx, packages/core-loader/src/live-mode/enableLiveMode.ts, packages/next-loader/src/defineLive.tsx, packages/next-loader/src/resolveCookiePerspective.ts, packages/next-loader/src/server-actions/index.ts, packages/next-loader/src/utils.ts, packages/react-loader/src/createQueryStore/server-only.ts, packages/react-loader/src/createQueryStore/universal.ts, packages/svelte-loader/src/createQueryStore.ts, packages/visual-editing/svelte/hooks.ts
Since https://github.com/sanity-io/client/pull/1007 the client warns when using `perspective: 'previewDrafts'`. This PR refactors to the new `perspective: 'drafts'` approach.
=> fix: replace `previewDrafts` with `drafts`

packages/next-loader/src/defineLive.tsx
The default value of `tags` is `['sanity']`, which is the current bonus tag we've always set, that provides an easy way to reset all the fetch cache related to `defineLive`:
```tsx
'use server'
import {revalidateTag} from 'next/cache'
export async function purgeSanityFetches() {
revalidateTag('sanity')
}
```
It's now possible to set your own custom tags when calling `sanityFetch`, which creates a progressive adoption path for projects currently using this approach: https://github.com/sanity-io/next-sanity?tab=readme-ov-file#tag-based-revalidation
It also creates a path for userland to combine the new live based approach, with an escape hatch for scenarios where there might not be a visitor in the next.js app when a mutation happens.
=> feat(sanityFetch): support custom cache `tags`

apps/remix/app/routes/shoes.$slug.tsx, apps/remix/app/routes/shoes._index.tsx, apps/remix/app/sanity.ts, packages/core-loader/src/live-mode/enableLiveMode.ts
Updates our internal remix implementation to show an example in how to fix https://github.com/sanity-io/sanity/issues/8985
This PR updates how we load the initial data in our remix example.
Using the perspective set by presentation tool into the presentation iframe in the query parameters, specifically `sanity-preview-perspective` 
By using this query param, we can get in the initial server response the correct data.
See how loading a page now shows in the initial load the correct document when used inside presentation.
We will also update the docs to reflect how to do this.
```ts
export const loader = async ({request}: {request: Request}) => {
const url = new URL(request.url)
const perspective = url.searchParams.get('sanity-preview-perspective')?.split(',') as
| ClientPerspective
| …
```
=> fix(remix): apply presentation perspective for initial server loader

apps/remix/app/LiveVisualEditing.tsx, apps/remix/app/root.tsx, apps/remix/app/routes/api.perspective.ts, apps/remix/app/routes/api.preview-mode.disable.ts, apps/remix/app/routes/api.preview-mode.enable.ts, apps/remix/app/routes/shoes.$slug.tsx, apps/remix/app/routes/shoes._index.tsx, apps/remix/app/sanity.ts, apps/remix/app/sessions.ts, apps/remix/package.json, apps/remix/turbo.json, apps/studio/sanity.config.ts, packages/@repo/env/index.ts, packages/core-loader/src/live-mode/enableLiveMode.ts, packages/core-loader/src/types.ts, packages/react-loader/src/defineUseLiveMode.ts, pnpm-lock.yaml
Also updates the remix example to use it to update a session cookie with the current selected perspective stack in the studio.
=> feat(core-loader): add onPerspective to live mode

packages/next-loader/package.json, packages/next-loader/src/client-components/live/SanityLive.tsx, packages/next-loader/src/defineLive.tsx, pnpm-lock.yaml
If Sanity Live Content API emits `goaway` then `<SanityLive>` will switch to long polling and automatically call `router.refresh()` every 30 seconds.
The interval can be changed, here to 10 seconds:
```tsx
<SanityLive intervalOnGoAway={10_000} />
```
It can be disabled:
```tsx
<SanityLive intervalOnGoAway={false} />
<SanityLive intervalOnGoAway={0} />
```
The event provides a `reason` string when the goaway happens, this can be accessed by providing a `onGoAway` event, which has to be a client function since `<SanityLive>` is a server component:
```ts
// ./client-functions.ts
'use client'
import {LiveEventGoAway} from '@sanity/client'
export function handleGoAway(event: LiveEventGoAway, intervalOnGoAway: number | false) {
console.log('Sanity Live connection closed, switching to long …
```
=> feat: implement long-polling on goaway

packages/comlink/src/node.ts, packages/comlink/src/util.ts
Adds a fallback implementation of `Promise.withResolvers` used in the `fetch` method on nodes. Error was reported for dashboard users on older versions of Safari.
=> fix(comlink): Promise.withResolvers shim

apps/live-next/package.json, apps/next-with-i18n/package.json, apps/next/package.json, apps/page-builder-demo/package.json, pnpm-lock.yaml
Now that [`next-sanity` has been updated](https://github.com/sanity-io/next-sanity/releases/tag/next-sanity-v9.12.0) to support the new [`plugins` API for visual editing overlays](https://github.com/sanity-io/visual-editing/releases/tag/visual-editing-v2.14.0), we should bump the `next-sanity` dep for next apps in this repo so they can utilize this new feature.
=> fix(deps): update next-sanity to 9.12.0 in apps
