sanity-io/visual-editing

packages/react-loader/src/createQueryStore.ts
Fixes #415 
Closes #416 
@thomasKn thanks for your original PR 💖
We're going with `useMemo` to save us an extra `useEffect` life cycle :)
=> fix(useQuery): snapshot state is now updated when initial changes

apps/common/src/utils.ts, apps/remix/app/root.tsx, apps/remix/app/routes/shoes.$slug.tsx, apps/remix/app/routes/shoes._index.tsx, apps/studio/sanity.config.ts, packages/presentation/src/preview/PreviewFrame.tsx, packages/presentation/src/reducers/presentationReducer.ts, packages/visual-editing/src/index.ts, packages/visual-editing/src/next-pages-router/VisualEditingComponent.tsx, packages/visual-editing/src/remix/VisualEditingComponent.tsx, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/Refresh.tsx, packages/visual-editing/src/ui/VisualEditing.tsx, packages/visual-editing/src/ui/enableVisualEditing.tsx
The API is undocumented until we've shipped the new `@sanity/presentation` in `sanity`
=> feat: add refresh API

packages/visual-editing/src/util/findNonInlineElement.ts, packages/visual-editing/src/util/findSanityNodes.ts
Forgot to refactor some now verbose types. 😬
=> refactor(visual-editing): improve element types

packages/channels/src/controller.ts, packages/channels/src/node.ts, packages/channels/src/types.ts, packages/core-loader/src/live-mode/enableLiveMode.ts, packages/presentation/src/PresentationTool.tsx, packages/presentation/src/editor/PostMessageRefreshMutations.tsx, packages/presentation/src/loader/LoaderQueries.tsx, packages/preview-kit-compat/src/useDocumentsInUse.ts, packages/visual-editing/src/ui/useChannel.tsx
Small type refactor in advance of CRX-546 (introducing channel protocol versioning).
=> refactor: improve channel types

apps/studio/locate.ts, apps/studio/presentation/DebugStega.tsx
Adds some missing specifiers for type only imports.
=> fix: studio app imports

packages/presentation/src/preview/PreviewFrame.tsx, packages/presentation/src/preview/PreviewLocationInput.tsx
Adjust the toolbar UI to align with UI changes to Structure with the introduction of Sanity UI v2.
=> fix(presentation): adjust toolbar item sizes and spacing

apps/page-builder-demo/.env.example, apps/page-builder-demo/next.config.mjs, apps/page-builder-demo/src/app/IndexPreview.tsx, apps/page-builder-demo/src/app/VisualEditing.tsx, apps/page-builder-demo/src/app/layout.tsx, apps/page-builder-demo/src/app/page.tsx, apps/page-builder-demo/src/app/product/[slug]/ProductPreview.tsx, apps/page-builder-demo/src/app/product/[slug]/page.tsx, apps/page-builder-demo/src/app/products/ProductsPreview.tsx, apps/page-builder-demo/src/app/products/page.tsx, apps/page-builder-demo/src/app/project/[slug]/ProjectPreview.tsx, apps/page-builder-demo/src/app/project/[slug]/page.tsx, apps/page-builder-demo/src/app/projects/ProjectsPreview.tsx, apps/page-builder-demo/src/app/projects/page.tsx, apps/page-builder-demo/src/sanity/client.ts, apps/page-builder-demo/src/sanity/store.ts, apps/page-builder-demo/tsconfig.json, pnpm-lock.yaml
Fixes hydration mismatch errors that frequently happened when working locally.
Also uses `loadQuery` to speedup load perf.
=> chore: fix page-builder-demo SSR hydration mismatch error

packages/presentation/src/components/ErrorCard.tsx, packages/presentation/src/document/LocationsBanner.tsx, packages/presentation/src/editor/ContentEditor.tsx, packages/presentation/src/editor/DocumentListPane.tsx, packages/presentation/src/editor/DocumentPane.tsx, packages/presentation/src/i18n/index.ts, packages/presentation/src/i18n/resources.ts, packages/presentation/src/plugin.tsx, packages/presentation/src/preview/PreviewFrame.tsx, packages/presentation/src/preview/PreviewLocationInput.tsx, packages/presentation/src/preview/ShareUrlMenuItems.tsx
First foray into using the i18n API so might require some testing! 😄
The string descriptions are also tedious, so feel free to suggest improvements.
=> feat(presentation): support i18n and add default locale resources

packages/channels/tsconfig.json, packages/core-loader/tsconfig.base.json, packages/core-loader/tsconfig.build.json, packages/overlays/tsconfig.base.json, packages/overlays/tsconfig.build.json, packages/presentation/tsconfig.json, packages/preview-kit-compat/tsconfig.base.json, packages/preview-kit-compat/tsconfig.build.json, packages/preview-url-secret/tsconfig.base.json, packages/preview-url-secret/tsconfig.build.json, packages/react-loader/tsconfig.base.json, packages/react-loader/tsconfig.build.json, packages/react-loader/tsconfig.json, packages/svelte-loader/tsconfig.base.json, packages/svelte-loader/tsconfig.build.json, packages/visual-editing-helpers/tsconfig.base.json, packages/visual-editing-helpers/tsconfig.build.json, packages/visual-editing/tsconfig.base.json, packages/visual-editing/tsconfig.build.json
Based on the setup in the https://github.com/sanity-io/sanity monorepo.
=> refactor: improve tsconfig settings

packages/visual-editing/README.md, packages/visual-editing/package.json, pnpm-lock.yaml
Hopefully this fixes the build issues in Astro 🙌
=> fix!: move `react` and `react-dom` to peer deps

packages/visual-editing/package.json
Otherwise the types are not properly exported.
=> fix(types): add react export to typeVersions

packages/presentation/package.json, packages/preview-url-secret/package.json, pnpm-lock.yaml
=> fix(deps): update dependency @sanity/icons to v3

packages/presentation/src/editor/ContentEditor.tsx
=> Fixed ContentEditor crashes

packages/presentation/src/useDocumentLocations.ts
Noticed some superfluous/duplicate checks in `useDocumentLocations` whilst comparing some Observable logic.
=> refactor(presentation): simplify `useDocumentLocations`

.prettierignore, packages/visual-editing/.eslintignore, packages/visual-editing/.gitignore, packages/visual-editing/turbo.json
This should [fix the build on `main`](https://vercel.com/sanity-sandbox/visual-editing-storybook/3NQCVXYd1mA6gpAkebVXfafUvPax) 🙌
=> chore: fix storybook build caching

.github/workflows/lint-fix.yml
Fixes build errors like these https://github.com/sanity-io/visual-editing/actions/runs/10634896303/job/29483293910
=> chore: fix lint command

.github/renovate.json, apps/common/src/env.ts, apps/next/next.config.mjs, apps/next/src/app/shoes/VisualEditing.tsx, apps/next/src/app/shoes/[slug]/page.client.tsx, apps/next/src/app/shoes/layout.tsx, apps/page-builder-demo/next.config.mjs, apps/studio/sanity.cli.ts, packages/presentation/src/getIntentState.ts, packages/presentation/src/usePreviewUrl.ts, packages/preview-url-secret/src/definePreviewUrl.ts, packages/preview-url-secret/src/types.ts, packages/visual-editing/src/ui/ElementOverlay.tsx
[More info](https://linear.app/sanity/issue/CRX-929/presentation-has-buggy-documentreferrer-behaviour)
=> fix: remove buggy `document.referrer` behaviour

release-please-config.json
Small change required to publish new comlink versions.
=> build: add comlink to release please config

apps/page-builder-demo/src/app/actions.ts, apps/page-builder-demo/src/app/alert-banner.tsx, apps/page-builder-demo/src/app/layout.tsx, apps/page-builder-demo/src/sanity.types.ts, packages/presentation/package.json, packages/presentation/src/i18n/resources.ts, packages/presentation/src/preview/PreviewFrame.tsx, packages/presentation/src/preview/ShareUrlDialog.tsx, packages/presentation/src/preview/ShareUrlMenuItems.tsx, pnpm-lock.yaml
Click "Share link" (replaces "Copy link"):
And you end up with this dialog:
=> feat: add qrcode of share url

.github/workflows/pr-validate.yml
Stolen from https://github.com/sanity-io/sanity/pull/7580 (thanks @binoy14!)
=> chore: validate PR titles for conventional commits

apps/page-builder-demo/src/sanity.types.ts, packages/visual-editing/src/controller.ts, packages/visual-editing/src/index.ts, packages/visual-editing/src/types.ts, packages/visual-editing/src/ui/ElementOverlay.tsx, packages/visual-editing/src/ui/OverlayDragGroupRect.tsx, packages/visual-editing/src/ui/OverlayDragPreview.tsx, packages/visual-editing/src/ui/Overlays.tsx, packages/visual-editing/src/ui/overlayStateReducer.ts, packages/visual-editing/src/util/dragAndDrop.ts, packages/visual-editing/src/util/geometry.ts
prevent scrollIntoView from firing while minimap open, fix group bounds overflow
=> chore(drag-and-drop): scroll-into-view, group bounds indicator fix

packages/visual-editing/src/ui/schema/SchemaProvider.tsx
Fixes an issue where union types were not being resolved correctly as the ref used to compare which paths have been resolved was set _before_ a response was received from Presentation. Now we more aggressively query for union types, meaning the context menu for array items should no longer show "Unknown type".
=> fix(visual-editing): always report document paths if unresolved

apps/next-with-i18n/package.json, packages/@repo/eslint-config/index.js, packages/insert-menu/.eslintrc.cjs, packages/insert-menu/package.json, pnpm-lock.yaml
I'm sick of [this](https://github.com/sanity-io/visual-editing/pull/1982) [fight](https://github.com/sanity-io/visual-editing/pull/1981)
=> chore: enough with prettier and eslint fighting

package.json
Adds release corel script to package.json file
=> chore: add `release:corel` script

knip.json, package.json, pnpm-lock.yaml
[Knip](https://knip.dev/) is pretty cool, I know this was considered a while back, and there were reports of too many false positives from other devs that had used this internally, but it looks to be generally pretty good on this repo. So opening this as a nice to have in case others are interested.
=> chore: add knip

packages/visual-editing/src/ui/optimistic-state/useDocuments.ts
The functions returned by the `useDocument` hook: `getDocument` and `mutateDocument` don't currently use `useCallback`.
Currently the only issue is unnecessary re-renders (`getDocument` is only used as a dependency in a single `useMemo` called in the `<ContextMenu>`) but the changes to be introduced in #2071 rely on stable identities.
=> fix(visual-editing): memoize `useDocuments` functions

packages/next-loader/src/client-components/live/SanityLive.tsx
Improves the clarity of the CORS origin error message
=> chore: improve cors origin error message

packages/visual-editing/src/ui/ElementOverlay.tsx
Relates to #2166, shoutout to @dagstuan for catching this! 💖
=> fix: support relative studioUrl origins

packages/presentation/src/index.ts, packages/presentation/src/types.ts, packages/presentation/src/useParams.ts, pnpm-lock.yaml
After some updates to the history tab in the sanity package, the useParams hook needed to be updated :)
Here's the updated behaviour (that was breaking before):
https://github.com/user-attachments/assets/9fa35e26-fd0f-4c41-9992-68d3a3c3eb2c
please double check the types situation 🙏
=> fix(presentation): fix issue where you couldn't open the review tab in the history of a document

packages/next-loader/src/defineLive.tsx
Small fix to adjust how stega is set in `SanityLiveStream` and `sanityFetch`.
Currently, the value passed as a prop/param is used if set, otherwise `stega` is set to true if:
- Draft mode is enabled.
With this PR, the value passed as a prop/param is used if set, otherwise `stega` is set to true if:
- Draft mode is enabled.
- The client config has a defined `stega.studioUrl`.
- `stega` has not been explicitly set to `false` when calling `defineLive`.
=> feat(next-loader): add option to disable stega in defineLive

apps/page-builder-demo/src/app/dnd/OptimisticSortOrder.tsx, apps/page-builder-demo/src/app/dnd/page.tsx, apps/page-builder-demo/src/sanity.types.ts, apps/studio/presentation/CustomNavigator.tsx
It ends up being a lot easier to use, and doesn't require `display: flex` or `display: grid` to work
=> chore: use React.Children instead of CSS

apps/next/src/app/shoes/sanity.ssr.ts
Tiny fix for the test Next app to correctly set the perspective during SSR.
=> chore(apps): correctly set next app ssr perspective

packages/@repo/env/index.ts, packages/@repo/eslint-config/package.json, packages/preview-url-secret/src/constants.ts, pnpm-lock.yaml
Adds support for [Content Releases API](https://www.sanity.io/docs/content-releases-api)
=> fix: upgrade `apiVersion` to `2025-02-19`

apps/live-next/sanity.types.ts, apps/page-builder-demo/src/sanity.types.ts, packages/visual-editing/src/ui/schema/SchemaContext.tsx, packages/visual-editing/src/ui/schema/SchemaProvider.tsx
[Before](https://visual-editing-studio.sanity.dev/page-builder-demo/presentation/page/d05edeb0-e774-4275-8e66-34f0e6daa372?preview=/%3Fsanity-preview-perspective%3Ddrafts) (note 8 identical requests are made)
[After](https://visual-editing-studio-git-fix-presentation-schema-over-fetching.sanity.dev/page-builder-demo/presentation/page/d05edeb0-e774-4275-8e66-34f0e6daa372?preview=/%3Fsanity-preview-perspective%3Ddrafts) (only 1 ✨ request)
=> fix: prevent over-fetching schema union types

packages/insert-menu/src/InsertMenu.tsx
When using the grid view for an array, blocks are misaligned if the title is long. 
| Before | After |
|--------|--------|
|<img width="552" height="412" alt="Screenshot 2025-07-29 at 09 41 02" src="https://github.com/user-attachments/assets/2e2389c1-d231-45b7-afba-95d37ae98ad8" />| <img width="547" height="408" alt="Screenshot 2025-07-29 at 09 41 23" src="https://github.com/user-attachments/assets/94535819-9551-4adc-8607-1549e298770d" />| 
Something else that is missing? 
Update any existing array schema in a Studio to use with view grid.
Example:
```ts
defineField({
name: 'polymorphicGridArray',
title: 'Polymorphic grid array',
description: 'An array of multiple types. options: {layout: "grid"}',
type: 'array',
options: {
layout: 'grid',
insertMenu: {
views: [{name: 'grid'}],
},
},
of: …
```
=> fix(insert-menu): grid items alignment is off for long titles
